// Generated by CoffeeScript 1.3.3
(function() {
  var World, zombie;

  zombie = require('zombie');

  World = function(callback) {
    this.browser = new zombie.Browser({
      site: 'http://localhost:8000/app/index.html#/'
    });
    this.visit = function(uri, callback) {
      return this.browser.visit(uri, callback);
    };
    return callback(this);
  };

  exports.World = World;

}).call(this);
