// Generated by CoffeeScript 1.3.3
(function() {
  'use strict';

  this.angular.module('myApp', ['myApp.filters', 'myApp.services', 'myApp.directives', 'ui.bootstrap', 'ui.bootstrap-carousel', 'conveyer-belt']).config([
    '$routeProvider', function($routeProvider) {
      $routeProvider.when('/view1', {
        templateUrl: 'partials/partial1.html',
        controller: CollectionCtrl
      }).when('/view2', {
        templateUrl: 'partials/partial2.html',
        controller: MyCtrl2
      }).when('/view3', {
        templateUrl: 'partials/partial3.html',
        controller: MyCtrl3
      }).otherwise({
        redirectTo: '/view1'
      });
    }
  ]);

}).call(this);