// Generated by CoffeeScript 1.3.3
(function() {
  'use strict';

  this.angular.module('myApp', ['myApp.filters', 'myApp.services', 'myApp.directives', 'ui.bootstrap', 'ui.bootstrap-carousel', 'conveyer-belt']).config([
    '$routeProvider', function($routeProvider) {
      $routeProvider.when('/view1', {
        templateUrl: 'partials/partial1.html',
        controller: CollectionCtrl
      }).when('/styleguide', {
        templateUrl: 'partials/styleguide.html',
        controller: StyleguideCtrl
      }).when('/notes', {
        templateUrl: 'partials/notes.html',
        controller: NotesCtrl
      }).otherwise({
        redirectTo: '/view1'
      });
    }
  ]);

}).call(this);