// Generated by CoffeeScript 1.3.3
(function() {
  'use strict';

  this.demoZippyCtrl = function($scope) {
    $scope.title = 'Description';
    $scope.text = 'These are the contents of a lesson set description.';
  }

  this.demoZippyCtrl.$inject = ['$scope'];

  this.CollectionCtrl = function($http, $scope) {
    $http.get('/data/lessonsets.json').success(function(data) {
      $scope.lessonSets = data;
    });
    $http.get('/data/tools.json').success(function(data){
      $scope.tools = data;
    })
  };

  this.CollectionCtrl.$inject = ['$http', '$scope'];

  this.LessonSetCtrl = function($scope) {
    $scope.showcaseLesson = {};
    $scope.$on('selection', function(event, args) {
      $scope.isShowcaseVisible = true;
      $scope.showcaseLesson = $scope.lessonSets[$scope.$index].lessons[args];
      angular.forEach($scope.showcaseLesson.resources, function(resource) {
        resource.url = 'partials/resources/' + resource.type.replace(/ /g,"_").toLowerCase() + '.html'
      })
    })
  };

  this.LessonSetCtrl.$inject = ['$scope'];

  this.ToolsCtrl = function($scope) {
  }

  this.ToolsCtrl.$inject = ['$scope'];

  this.MyCtrl2 = function($scope) {
    $scope.filter = 'semantic';
    $scope.isVisible = function(value) {
      if(value==$scope.filter) {
        return true;
      }
    }
    $scope.search = function(filter) {
      $scope.filter = filter;
    }
    $scope.presentation = [
      {
        "title": "Colors",
        "content": "partials/styleguide/colors.html"
      },
      {
        "title": "Type",
        "content": "partials/styleguide/type.html"
      }
    ]
    $scope.semantic = [
      {
        "title": "Concepts",
        "content": "partials/styleguide/concepts.html"
      },
      {
        "title": "Widgets",
        "content": "partials/styleguide/widgets.html"
      },
      {
        "title": "Modules",
        "content": "partials/styleguide/modules.html"
      }
    ]
  };

  this.MyCtrl2.$inject = ['$scope'];

  this.MyCtrl3 = function($scope) {

  };

  this.MyCtrl3.$inject = ['$scope'];

}).call(this);
