// Generated by CoffeeScript 1.3.3
(function() {
  'use strict';

  this.demoZippyCtrl = function($scope) {
    $scope.title = 'Description';
    $scope.text = 'These are the contents of a lesson set description.';
  }

  this.demoZippyCtrl.$inject = ['$scope'];

  this.CollectionCtrl = function($http, $scope) {
    $http.get('/data/lessonsets.json').success(function(data) {
      $scope.lessonSets = data;
    });
    $http.get('/data/tools.json').success(function(data){
      $scope.tools = data;
    })
  };

  this.CollectionCtrl.$inject = ['$http', '$scope'];

  this.LessonSetCtrl = function($scope) {
    $scope.showcaseLesson = {};
    $scope.$on('selection', function(event, args) {
      $scope.isShowcaseVisible = true;
      $scope.showcaseLesson = $scope.lessonSets[$scope.$index].lessons[args];
      angular.forEach($scope.showcaseLesson.resources, function(resource) {
        resource.url = 'partials/resources/' + resource.type.replace(/ /g,"_").toLowerCase() + '.html'
      })
    })
  };

  this.LessonSetCtrl.$inject = ['$scope'];

  this.ToolsCtrl = function($scope) {
  }

  this.ToolsCtrl.$inject = ['$scope'];

  this.StyleguideCtrl = function($scope) {
    $scope.filter = 'general';
    $scope.isVisible = function(value) {
      if(value==$scope.filter) {
        return true;
      }
    }
    $scope.search = function(filter) {
      $scope.filter = filter;
    }
    $scope.general = [
      {
        "title": "Colors",
        "content": "partials/styleguide/colors.html"
      },
      {
        "title": "Grid",
        "content": "partials/styleguide/grid.html"
      },
      {
        "title": "Type",
        "content": "partials/styleguide/type.html"
      },
      {
        "title": "Icons",
        "content": "partials/styleguide/icons.html"
      },
      {
        "title": "Buttons",
        "content": "partials/styleguide/buttons.html"
      },
      {
        "title": "Containers",
        "content": "partials/styleguide/containers.html"
      },
      {
        "title": "Forms",
        "content": "partials/styleguide/forms.html"
      },
      {
        "title": "Navigation",
        "content": "partials/styleguide/navigation.html"
      },
      {
        "title": "Widgets",
        "content": "partials/styleguide/widgets.html"
      },
      {
        "title": "Miscellaneous",
        "content": "partials/styleguide/miscellaneous.html"
      }
    ]
    $scope.lz_specific = [
      {
        "title": "Concepts",
        "content": "partials/styleguide/concepts.html"
      },
      {
        "title": "Modules",
        "content": "partials/styleguide/modules.html"
      }
    ]
  };

  this.StyleguideCtrl.$inject = ['$scope'];

  this.NotesCtrl = function($scope) {

  };

  this.NotesCtrl.$inject = ['$scope'];

  this.MainCtrl = function($scope, $location) {
    $scope.getClass = function(path) {
        if ($location.path().substr(0, path.length) == path) {
          return "active"
        } else {
          return ""
        }
    }
  };

  this.MainCtrl.$inject = ['$scope', '$location'];

}).call(this);
