// Generated by CoffeeScript 1.3.3
(function() {

  describe('MyCtrl1', function() {
    var myCtrl1;
    myCtrl1 = null;
    beforeEach(function() {
      return myCtrl1 = new MyCtrl1();
    });
    return it('should ....', function() {});
  });

}).call(this);
