// Generated by CoffeeScript 1.3.3
(function() {

  describe('posboss app', function() {
    return beforeEach(function() {
      return browser().navigateTo('../../app/index.html');
    });
  });

}).call(this);
